/**
 * CrowdLabelAPI
 * API for CrowdLabel
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrowdLabelApi);
  }
}(this, function(expect, CrowdLabelApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrowdLabelApi.UsersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersApi', function() {
    describe('availabilityUsersAvailabilityPut', function() {
      it('should call availabilityUsersAvailabilityPut successfully', function(done) {
        //uncomment below and update the code to test availabilityUsersAvailabilityPut
        //instance.availabilityUsersAvailabilityPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editCreditsUsersMeCreditsPost', function() {
      it('should call editCreditsUsersMeCreditsPost successfully', function(done) {
        //uncomment below and update the code to test editCreditsUsersMeCreditsPost
        //instance.editCreditsUsersMeCreditsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editMeUsersMePatch', function() {
      it('should call editMeUsersMePatch successfully', function(done) {
        //uncomment below and update the code to test editMeUsersMePatch
        //instance.editMeUsersMePatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMeUsersMeGet', function() {
      it('should call getMeUsersMeGet successfully', function(done) {
        //uncomment below and update the code to test getMeUsersMeGet
        //instance.getMeUsersMeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserUsersUsernameGet', function() {
      it('should call getUserUsersUsernameGet successfully', function(done) {
        //uncomment below and update the code to test getUserUsersUsernameGet
        //instance.getUserUsersUsernameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerUsersRegisterPost', function() {
      it('should call registerUsersRegisterPost successfully', function(done) {
        //uncomment below and update the code to test registerUsersRegisterPost
        //instance.registerUsersRegisterPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('verifyEmailUsersVerifyEmailPost', function() {
      it('should call verifyEmailUsersVerifyEmailPost successfully', function(done) {
        //uncomment below and update the code to test verifyEmailUsersVerifyEmailPost
        //instance.verifyEmailUsersVerifyEmailPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
