/**
 * CrowdLabelAPI
 * API for CrowdLabel
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrowdLabelApi);
  }
}(this, function(expect, CrowdLabelApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrowdLabelApi.Task();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Task', function() {
    it('should create an instance of Task', function() {
      // uncomment below and update the code to test Task
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be.a(CrowdLabelApi.Task);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be();
    });

    it('should have the property credits (base name: "credits")', function() {
      // uncomment below and update the code to test the property credits
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be();
    });

    it('should have the property introduction (base name: "introduction")', function() {
      // uncomment below and update the code to test the property introduction
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be();
    });

    it('should have the property coverImage (base name: "cover_image")', function() {
      // uncomment below and update the code to test the property coverImage
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be();
    });

    it('should have the property responsesRequired (base name: "responses_required")', function() {
      // uncomment below and update the code to test the property responsesRequired
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be();
    });

    it('should have the property questions (base name: "questions")', function() {
      // uncomment below and update the code to test the property questions
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be();
    });

    it('should have the property taskId (base name: "task_id")', function() {
      // uncomment below and update the code to test the property taskId
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be();
    });

    it('should have the property requester (base name: "requester")', function() {
      // uncomment below and update the code to test the property requester
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be();
    });

    it('should have the property dateCreated (base name: "date_created")', function() {
      // uncomment below and update the code to test the property dateCreated
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be();
    });

    it('should have the property resourcePath (base name: "resource_path")', function() {
      // uncomment below and update the code to test the property resourcePath
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be();
    });

    it('should have the property respondentsClaimed (base name: "respondents_claimed")', function() {
      // uncomment below and update the code to test the property respondentsClaimed
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be();
    });

    it('should have the property respondentsCompleted (base name: "respondents_completed")', function() {
      // uncomment below and update the code to test the property respondentsCompleted
      //var instance = new CrowdLabelApi.Task();
      //expect(instance).to.be();
    });

  });

}));
