/**
 * CrowdLabelAPI
 * API for CrowdLabel
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrowdLabelApi);
  }
}(this, function(expect, CrowdLabelApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrowdLabelApi.TaskSearchRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TaskSearchRequest', function() {
    it('should create an instance of TaskSearchRequest', function() {
      // uncomment below and update the code to test TaskSearchRequest
      //var instance = new CrowdLabelApi.TaskSearchRequest();
      //expect(instance).to.be.a(CrowdLabelApi.TaskSearchRequest);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new CrowdLabelApi.TaskSearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new CrowdLabelApi.TaskSearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property requesters (base name: "requesters")', function() {
      // uncomment below and update the code to test the property requesters
      //var instance = new CrowdLabelApi.TaskSearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property page (base name: "page")', function() {
      // uncomment below and update the code to test the property page
      //var instance = new CrowdLabelApi.TaskSearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property pageSize (base name: "page_size")', function() {
      // uncomment below and update the code to test the property pageSize
      //var instance = new CrowdLabelApi.TaskSearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property creditsMin (base name: "credits_min")', function() {
      // uncomment below and update the code to test the property creditsMin
      //var instance = new CrowdLabelApi.TaskSearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property creditsMax (base name: "credits_max")', function() {
      // uncomment below and update the code to test the property creditsMax
      //var instance = new CrowdLabelApi.TaskSearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property sortCriteria (base name: "sort_criteria")', function() {
      // uncomment below and update the code to test the property sortCriteria
      //var instance = new CrowdLabelApi.TaskSearchRequest();
      //expect(instance).to.be();
    });

    it('should have the property sortAscending (base name: "sort_ascending")', function() {
      // uncomment below and update the code to test the property sortAscending
      //var instance = new CrowdLabelApi.TaskSearchRequest();
      //expect(instance).to.be();
    });

  });

}));
