/**
 * CrowdLabelAPI
 * API for CrowdLabel
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Answer from './model/Answer';
import Answer1 from './model/Answer1';
import AvailabilityRequest from './model/AvailabilityRequest';
import AvailabilityResponse from './model/AvailabilityResponse';
import BoundingBoxAnswer from './model/BoundingBoxAnswer';
import EditEmailRequest from './model/EditEmailRequest';
import EditPasswordRequest from './model/EditPasswordRequest';
import Email from './model/Email';
import ErrorResponse from './model/ErrorResponse';
import HTTPValidationError from './model/HTTPValidationError';
import LocationInner from './model/LocationInner';
import MultiChoiceAnswer from './model/MultiChoiceAnswer';
import NewInfo from './model/NewInfo';
import OpenAnswer from './model/OpenAnswer';
import Point from './model/Point';
import Question from './model/Question';
import RankingAnswer from './model/RankingAnswer';
import RegistrationError from './model/RegistrationError';
import RegistrationRequest from './model/RegistrationRequest';
import SingleChoiceAnswer from './model/SingleChoiceAnswer';
import Task from './model/Task';
import TaskSearchRequest from './model/TaskSearchRequest';
import TaskSearchResponse from './model/TaskSearchResponse';
import Token from './model/Token';
import User from './model/User';
import ValidationError from './model/ValidationError';
import AuthApi from './api/AuthApi';
import QuestionsApi from './api/QuestionsApi';
import TasksApi from './api/TasksApi';
import UsersApi from './api/UsersApi';


/**
* API for CrowdLabel.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CrowdLabelApi = require('index'); // See note below*.
* var xxxSvc = new CrowdLabelApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CrowdLabelApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CrowdLabelApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CrowdLabelApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Answer model constructor.
     * @property {module:model/Answer}
     */
    Answer,

    /**
     * The Answer1 model constructor.
     * @property {module:model/Answer1}
     */
    Answer1,

    /**
     * The AvailabilityRequest model constructor.
     * @property {module:model/AvailabilityRequest}
     */
    AvailabilityRequest,

    /**
     * The AvailabilityResponse model constructor.
     * @property {module:model/AvailabilityResponse}
     */
    AvailabilityResponse,

    /**
     * The BoundingBoxAnswer model constructor.
     * @property {module:model/BoundingBoxAnswer}
     */
    BoundingBoxAnswer,

    /**
     * The EditEmailRequest model constructor.
     * @property {module:model/EditEmailRequest}
     */
    EditEmailRequest,

    /**
     * The EditPasswordRequest model constructor.
     * @property {module:model/EditPasswordRequest}
     */
    EditPasswordRequest,

    /**
     * The Email model constructor.
     * @property {module:model/Email}
     */
    Email,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The HTTPValidationError model constructor.
     * @property {module:model/HTTPValidationError}
     */
    HTTPValidationError,

    /**
     * The LocationInner model constructor.
     * @property {module:model/LocationInner}
     */
    LocationInner,

    /**
     * The MultiChoiceAnswer model constructor.
     * @property {module:model/MultiChoiceAnswer}
     */
    MultiChoiceAnswer,

    /**
     * The NewInfo model constructor.
     * @property {module:model/NewInfo}
     */
    NewInfo,

    /**
     * The OpenAnswer model constructor.
     * @property {module:model/OpenAnswer}
     */
    OpenAnswer,

    /**
     * The Point model constructor.
     * @property {module:model/Point}
     */
    Point,

    /**
     * The Question model constructor.
     * @property {module:model/Question}
     */
    Question,

    /**
     * The RankingAnswer model constructor.
     * @property {module:model/RankingAnswer}
     */
    RankingAnswer,

    /**
     * The RegistrationError model constructor.
     * @property {module:model/RegistrationError}
     */
    RegistrationError,

    /**
     * The RegistrationRequest model constructor.
     * @property {module:model/RegistrationRequest}
     */
    RegistrationRequest,

    /**
     * The SingleChoiceAnswer model constructor.
     * @property {module:model/SingleChoiceAnswer}
     */
    SingleChoiceAnswer,

    /**
     * The Task model constructor.
     * @property {module:model/Task}
     */
    Task,

    /**
     * The TaskSearchRequest model constructor.
     * @property {module:model/TaskSearchRequest}
     */
    TaskSearchRequest,

    /**
     * The TaskSearchResponse model constructor.
     * @property {module:model/TaskSearchResponse}
     */
    TaskSearchResponse,

    /**
     * The Token model constructor.
     * @property {module:model/Token}
     */
    Token,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The QuestionsApi service constructor.
    * @property {module:api/QuestionsApi}
    */
    QuestionsApi,

    /**
    * The TasksApi service constructor.
    * @property {module:api/TasksApi}
    */
    TasksApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
