/**
 * CrowdLabelAPI
 * API for CrowdLabel
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Answer from '../model/Answer';
import Answer1 from '../model/Answer1';
import ErrorResponse from '../model/ErrorResponse';
import HTTPValidationError from '../model/HTTPValidationError';

/**
* Questions service.
* @module api/QuestionsApi
* @version 0.1.0
*/
export default class QuestionsApi {

    /**
    * Constructs a new QuestionsApi. 
    * @alias module:api/QuestionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createAnswerTasksTaskIdQuestionsQuestionIdAnswerPut operation.
     * @callback module:api/QuestionsApi~createAnswerTasksTaskIdQuestionsQuestionIdAnswerPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Answer} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Answer
     * @param {Number} taskId 
     * @param {Number} questionId 
     * @param {module:model/Answer1} answer1 
     * @param {module:api/QuestionsApi~createAnswerTasksTaskIdQuestionsQuestionIdAnswerPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Answer}
     */
    createAnswerTasksTaskIdQuestionsQuestionIdAnswerPut(taskId, questionId, answer1, callback) {
      let postBody = answer1;
      // verify the required parameter 'taskId' is set
      if (taskId === undefined || taskId === null) {
        throw new Error("Missing the required parameter 'taskId' when calling createAnswerTasksTaskIdQuestionsQuestionIdAnswerPut");
      }
      // verify the required parameter 'questionId' is set
      if (questionId === undefined || questionId === null) {
        throw new Error("Missing the required parameter 'questionId' when calling createAnswerTasksTaskIdQuestionsQuestionIdAnswerPut");
      }
      // verify the required parameter 'answer1' is set
      if (answer1 === undefined || answer1 === null) {
        throw new Error("Missing the required parameter 'answer1' when calling createAnswerTasksTaskIdQuestionsQuestionIdAnswerPut");
      }

      let pathParams = {
        'task_id': taskId,
        'question_id': questionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Answer;
      return this.apiClient.callApi(
        '/tasks/{task_id}/questions/{question_id}/answer', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getQuestionTasksTaskIdQuestionsQuestionIdGet operation.
     * @callback module:api/QuestionsApi~getQuestionTasksTaskIdQuestionsQuestionIdGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Question
     * @param {Number} questionId 
     * @param {Number} taskId 
     * @param {Object} opts Optional parameters
     * @param {Array.<Object>} opts.requestBody 
     * @param {module:api/QuestionsApi~getQuestionTasksTaskIdQuestionsQuestionIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getQuestionTasksTaskIdQuestionsQuestionIdGet(questionId, taskId, opts, callback) {
      opts = opts || {};
      let postBody = opts['requestBody'];
      // verify the required parameter 'questionId' is set
      if (questionId === undefined || questionId === null) {
        throw new Error("Missing the required parameter 'questionId' when calling getQuestionTasksTaskIdQuestionsQuestionIdGet");
      }
      // verify the required parameter 'taskId' is set
      if (taskId === undefined || taskId === null) {
        throw new Error("Missing the required parameter 'taskId' when calling getQuestionTasksTaskIdQuestionsQuestionIdGet");
      }

      let pathParams = {
        'question_id': questionId,
        'task_id': taskId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/tasks/{task_id}/questions/{question_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
