/**
 * CrowdLabelAPI
 * API for CrowdLabel
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import HTTPValidationError from '../model/HTTPValidationError';
import Question from '../model/Question';
import Task from '../model/Task';
import TaskSearchRequest from '../model/TaskSearchRequest';
import TaskSearchResponse from '../model/TaskSearchResponse';

/**
* Tasks service.
* @module api/TasksApi
* @version 0.1.0
*/
export default class TasksApi {

    /**
    * Constructs a new TasksApi. 
    * @alias module:api/TasksApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the claimTaskTasksTaskIdClaimPost operation.
     * @callback module:api/TasksApi~claimTaskTasksTaskIdClaimPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Task} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Claim Task
     * @param {Number} taskId 
     * @param {module:api/TasksApi~claimTaskTasksTaskIdClaimPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Task}
     */
    claimTaskTasksTaskIdClaimPost(taskId, callback) {
      let postBody = null;
      // verify the required parameter 'taskId' is set
      if (taskId === undefined || taskId === null) {
        throw new Error("Missing the required parameter 'taskId' when calling claimTaskTasksTaskIdClaimPost");
      }

      let pathParams = {
        'task_id': taskId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Task;
      return this.apiClient.callApi(
        '/tasks/{task_id}/claim', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the completeTasksTaskIdCompletePost operation.
     * @callback module:api/TasksApi~completeTasksTaskIdCompletePostCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Complete
     * For the respondent to mark the task as completed
     * @param {Number} taskId 
     * @param {module:api/TasksApi~completeTasksTaskIdCompletePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    completeTasksTaskIdCompletePost(taskId, callback) {
      let postBody = null;
      // verify the required parameter 'taskId' is set
      if (taskId === undefined || taskId === null) {
        throw new Error("Missing the required parameter 'taskId' when calling completeTasksTaskIdCompletePost");
      }

      let pathParams = {
        'task_id': taskId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/tasks/{task_id}/complete', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteTaskTasksTaskIdDelete operation.
     * @callback module:api/TasksApi~deleteTaskTasksTaskIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Task
     * @param {Number} taskId 
     * @param {module:api/TasksApi~deleteTaskTasksTaskIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    deleteTaskTasksTaskIdDelete(taskId, callback) {
      let postBody = null;
      // verify the required parameter 'taskId' is set
      if (taskId === undefined || taskId === null) {
        throw new Error("Missing the required parameter 'taskId' when calling deleteTaskTasksTaskIdDelete");
      }

      let pathParams = {
        'task_id': taskId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/tasks/{task_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the downloadTaskResultsTasksTaskIdDownloadGet operation.
     * @callback module:api/TasksApi~downloadTaskResultsTasksTaskIdDownloadGetCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Download Task Results
     * Download results
     * @param {Number} taskId 
     * @param {module:api/TasksApi~downloadTaskResultsTasksTaskIdDownloadGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    downloadTaskResultsTasksTaskIdDownloadGet(taskId, callback) {
      let postBody = null;
      // verify the required parameter 'taskId' is set
      if (taskId === undefined || taskId === null) {
        throw new Error("Missing the required parameter 'taskId' when calling downloadTaskResultsTasksTaskIdDownloadGet");
      }

      let pathParams = {
        'task_id': taskId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/tasks/{task_id}/download', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCoverTasksTaskIdCoverImageGet operation.
     * @callback module:api/TasksApi~getCoverTasksTaskIdCoverImageGetCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Cover
     * Get cover image
     * @param {Number} taskId 
     * @param {module:api/TasksApi~getCoverTasksTaskIdCoverImageGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    getCoverTasksTaskIdCoverImageGet(taskId, callback) {
      let postBody = null;
      // verify the required parameter 'taskId' is set
      if (taskId === undefined || taskId === null) {
        throw new Error("Missing the required parameter 'taskId' when calling getCoverTasksTaskIdCoverImageGet");
      }

      let pathParams = {
        'task_id': taskId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/tasks/{task_id}/cover-image', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getProgressTasksTaskIdProgressGet operation.
     * @callback module:api/TasksApi~getProgressTasksTaskIdProgressGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Progress
     * Respondent's progress within a task, which is the highest index answered question. -1 if no questions have been answered yet.
     * @param {Object} taskId 
     * @param {module:api/TasksApi~getProgressTasksTaskIdProgressGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getProgressTasksTaskIdProgressGet(taskId, callback) {
      let postBody = null;
      // verify the required parameter 'taskId' is set
      if (taskId === undefined || taskId === null) {
        throw new Error("Missing the required parameter 'taskId' when calling getProgressTasksTaskIdProgressGet");
      }

      let pathParams = {
        'task_id': taskId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/tasks/{task_id}/progress', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTaskTasksTaskIdGet operation.
     * @callback module:api/TasksApi~getTaskTasksTaskIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Task} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Task
     * Get a task based on its task_id
     * @param {Number} taskId 
     * @param {module:api/TasksApi~getTaskTasksTaskIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Task}
     */
    getTaskTasksTaskIdGet(taskId, callback) {
      let postBody = null;
      // verify the required parameter 'taskId' is set
      if (taskId === undefined || taskId === null) {
        throw new Error("Missing the required parameter 'taskId' when calling getTaskTasksTaskIdGet");
      }

      let pathParams = {
        'task_id': taskId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Task;
      return this.apiClient.callApi(
        '/tasks/{task_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchTasksTasksPut operation.
     * @callback module:api/TasksApi~searchTasksTasksPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TaskSearchResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search Tasks
     * Gets the tasks matching the search criteria  Returns: list of `Task`s matching the query within the specified `page` and `page_size`, and total number of `Task`s matching the query          The following are all valid search parameters:  `name`: name of the task, empty name searches for any task  `tags`: keywords that identify the type of task, for example \"object-detection\"  `requesters`: username of the requesters who created task, empty searches for any requester  `credits_min`, `credits_max`: minimum and maximum number of credits rewarded upon task completion; negative `credits_max` implies no upper limit  `questions_min`, `questions_max`: minimum and maximum number of questions in the task; negative `questions_max` implies no upper limit  `page`: the page; negative value counts backwards, e.g. -1 returns the last page  `page_size`: the size of each page; if -1 then `page` would not be considered and all results will be returned, e.g.:  - if `page` is 2 and `page_size` is 10, then it will return the 11th to 20th results, inclusive  - if `page` is _ and `page_size` is -1, then it will return all the results  - if `page` is -1, `page_size` is 10, and there are 26 results in total, then it will return the 21st to 26th results, inclusive  `sort_criteria`: search parameter that the results should be sorted against  `sort_ascending`: True to sort in ascending order, False to sort in descending order
     * @param {module:model/TaskSearchRequest} taskSearchRequest 
     * @param {module:api/TasksApi~searchTasksTasksPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TaskSearchResponse}
     */
    searchTasksTasksPut(taskSearchRequest, callback) {
      let postBody = taskSearchRequest;
      // verify the required parameter 'taskSearchRequest' is set
      if (taskSearchRequest === undefined || taskSearchRequest === null) {
        throw new Error("Missing the required parameter 'taskSearchRequest' when calling searchTasksTasksPut");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaskSearchResponse;
      return this.apiClient.callApi(
        '/tasks/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the uploadTaskTasksUploadPost operation.
     * @callback module:api/TasksApi~uploadTaskTasksUploadPostCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Question>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Upload Task
     * @param {File} taskFile 
     * @param {module:api/TasksApi~uploadTaskTasksUploadPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Question>}
     */
    uploadTaskTasksUploadPost(taskFile, callback) {
      let postBody = null;
      // verify the required parameter 'taskFile' is set
      if (taskFile === undefined || taskFile === null) {
        throw new Error("Missing the required parameter 'taskFile' when calling uploadTaskTasksUploadPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'task_file': taskFile
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = [Question];
      return this.apiClient.callApi(
        '/tasks/upload', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
