/**
 * CrowdLabelAPI
 * API for CrowdLabel
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Admin model module.
 * @module model/Admin
 * @version 0.1.0
 */
class Admin {
    /**
     * Constructs a new <code>Admin</code>.
     * @alias module:model/Admin
     * @param email {String} 
     * @param username {String} 
     * @param dateCreated {Date} 
     */
    constructor(email, username, dateCreated) { 
        
        Admin.initialize(this, email, username, dateCreated);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, username, dateCreated) { 
        obj['email'] = email;
        obj['username'] = username;
        obj['date_created'] = dateCreated;
    }

    /**
     * Constructs a <code>Admin</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Admin} obj Optional instance to populate.
     * @return {module:model/Admin} The populated <code>Admin</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Admin();

            if (data.hasOwnProperty('user_type')) {
                obj['user_type'] = ApiClient.convertToType(data['user_type'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('credits')) {
                obj['credits'] = ApiClient.convertToType(data['credits'], 'Number');
            }
            if (data.hasOwnProperty('date_created')) {
                obj['date_created'] = ApiClient.convertToType(data['date_created'], 'Date');
            }
            if (data.hasOwnProperty('password_hashed')) {
                obj['password_hashed'] = ApiClient.convertToType(data['password_hashed'], 'String');
            }
            if (data.hasOwnProperty('tested')) {
                obj['tested'] = ApiClient.convertToType(data['tested'], 'Boolean');
            }
            if (data.hasOwnProperty('tasks_claimed')) {
                obj['tasks_claimed'] = ApiClient.convertToType(data['tasks_claimed'], ['Number']);
            }
            if (data.hasOwnProperty('tasks_completed')) {
                obj['tasks_completed'] = ApiClient.convertToType(data['tasks_completed'], ['Number']);
            }
            if (data.hasOwnProperty('tasks_requested')) {
                obj['tasks_requested'] = ApiClient.convertToType(data['tasks_requested'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Admin</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Admin</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Admin.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['user_type'] && !(typeof data['user_type'] === 'string' || data['user_type'] instanceof String)) {
            throw new Error("Expected the field `user_type` to be a primitive type in the JSON string but got " + data['user_type']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['password_hashed'] && !(typeof data['password_hashed'] === 'string' || data['password_hashed'] instanceof String)) {
            throw new Error("Expected the field `password_hashed` to be a primitive type in the JSON string but got " + data['password_hashed']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tasks_claimed'])) {
            throw new Error("Expected the field `tasks_claimed` to be an array in the JSON data but got " + data['tasks_claimed']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tasks_completed'])) {
            throw new Error("Expected the field `tasks_completed` to be an array in the JSON data but got " + data['tasks_completed']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tasks_requested'])) {
            throw new Error("Expected the field `tasks_requested` to be an array in the JSON data but got " + data['tasks_requested']);
        }

        return true;
    }


}

Admin.RequiredProperties = ["email", "username", "date_created"];

/**
 * @member {String} user_type
 * @default 'admin'
 */
Admin.prototype['user_type'] = 'admin';

/**
 * @member {String} email
 */
Admin.prototype['email'] = undefined;

/**
 * @member {String} username
 */
Admin.prototype['username'] = undefined;

/**
 * @member {Number} credits
 * @default 0
 */
Admin.prototype['credits'] = 0;

/**
 * @member {Date} date_created
 */
Admin.prototype['date_created'] = undefined;

/**
 * @member {String} password_hashed
 * @default ''
 */
Admin.prototype['password_hashed'] = '';

/**
 * @member {Boolean} tested
 * @default false
 */
Admin.prototype['tested'] = false;

/**
 * @member {Array.<Number>} tasks_claimed
 */
Admin.prototype['tasks_claimed'] = undefined;

/**
 * @member {Array.<Number>} tasks_completed
 */
Admin.prototype['tasks_completed'] = undefined;

/**
 * @member {Array.<Number>} tasks_requested
 */
Admin.prototype['tasks_requested'] = undefined;






export default Admin;

