/**
 * CrowdLabelAPI
 * API for CrowdLabel
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Answer model module.
 * @module model/Answer
 * @version 0.1.0
 */
class Answer {
    /**
     * Constructs a new <code>Answer</code>.
     * @alias module:model/Answer
     * @param respondent {String} 
     * @param dateAnswered {Date} 
     * @param taskId {Number} 
     * @param questionId {Number} 
     * @param questionType {Number} 
     */
    constructor(respondent, dateAnswered, taskId, questionId, questionType) { 
        
        Answer.initialize(this, respondent, dateAnswered, taskId, questionId, questionType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, respondent, dateAnswered, taskId, questionId, questionType) { 
        obj['respondent'] = respondent;
        obj['date_answered'] = dateAnswered;
        obj['task_id'] = taskId;
        obj['question_id'] = questionId;
        obj['question_type'] = questionType;
    }

    /**
     * Constructs a <code>Answer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Answer} obj Optional instance to populate.
     * @return {module:model/Answer} The populated <code>Answer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Answer();

            if (data.hasOwnProperty('respondent')) {
                obj['respondent'] = ApiClient.convertToType(data['respondent'], 'String');
            }
            if (data.hasOwnProperty('date_answered')) {
                obj['date_answered'] = ApiClient.convertToType(data['date_answered'], 'Date');
            }
            if (data.hasOwnProperty('task_id')) {
                obj['task_id'] = ApiClient.convertToType(data['task_id'], 'Number');
            }
            if (data.hasOwnProperty('question_id')) {
                obj['question_id'] = ApiClient.convertToType(data['question_id'], 'Number');
            }
            if (data.hasOwnProperty('question_type')) {
                obj['question_type'] = ApiClient.convertToType(data['question_type'], 'Number');
            }
            if (data.hasOwnProperty('answer')) {
                obj['answer'] = ApiClient.convertToType(data['answer'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Answer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Answer</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Answer.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['respondent'] && !(typeof data['respondent'] === 'string' || data['respondent'] instanceof String)) {
            throw new Error("Expected the field `respondent` to be a primitive type in the JSON string but got " + data['respondent']);
        }

        return true;
    }


}

Answer.RequiredProperties = ["respondent", "date_answered", "task_id", "question_id", "question_type"];

/**
 * @member {String} respondent
 */
Answer.prototype['respondent'] = undefined;

/**
 * @member {Date} date_answered
 */
Answer.prototype['date_answered'] = undefined;

/**
 * @member {Number} task_id
 */
Answer.prototype['task_id'] = undefined;

/**
 * @member {Number} question_id
 */
Answer.prototype['question_id'] = undefined;

/**
 * @member {Number} question_type
 */
Answer.prototype['question_type'] = undefined;

/**
 * @member {Object} answer
 */
Answer.prototype['answer'] = undefined;






export default Answer;

