/**
 * CrowdLabelAPI
 * API for CrowdLabel
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BoundingBoxAnswer from './BoundingBoxAnswer';
import Corners from './Corners';
import MultiChoiceAnswer from './MultiChoiceAnswer';
import OpenAnswer from './OpenAnswer';
import RankingAnswer from './RankingAnswer';
import SingleChoiceAnswer from './SingleChoiceAnswer';
// TODO: add anyof model support
