/**
 * CrowdLabelAPI
 * API for CrowdLabel
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MultiChoiceAnswer model module.
 * @module model/MultiChoiceAnswer
 * @version 0.1.0
 */
class MultiChoiceAnswer {
    /**
     * Constructs a new <code>MultiChoiceAnswer</code>.
     * @alias module:model/MultiChoiceAnswer
     * @param choices {Array.<Number>} 
     */
    constructor(choices) { 
        
        MultiChoiceAnswer.initialize(this, choices);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, choices) { 
        obj['choices'] = choices;
    }

    /**
     * Constructs a <code>MultiChoiceAnswer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MultiChoiceAnswer} obj Optional instance to populate.
     * @return {module:model/MultiChoiceAnswer} The populated <code>MultiChoiceAnswer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MultiChoiceAnswer();

            if (data.hasOwnProperty('choices')) {
                obj['choices'] = ApiClient.convertToType(data['choices'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MultiChoiceAnswer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MultiChoiceAnswer</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MultiChoiceAnswer.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['choices'])) {
            throw new Error("Expected the field `choices` to be an array in the JSON data but got " + data['choices']);
        }

        return true;
    }


}

MultiChoiceAnswer.RequiredProperties = ["choices"];

/**
 * @member {Array.<Number>} choices
 */
MultiChoiceAnswer.prototype['choices'] = undefined;






export default MultiChoiceAnswer;

