/**
 * CrowdLabelAPI
 * API for CrowdLabel
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Answer from './Answer';
import BoundingBoxQuestion from './BoundingBoxQuestion';
import MultiChoiceQuestion from './MultiChoiceQuestion';
import OpenQuestion from './OpenQuestion';
import RankingQuestion from './RankingQuestion';
import SingleChoiceQuestion from './SingleChoiceQuestion';
// TODO: add anyof model support
