/**
 * CrowdLabelAPI
 * API for CrowdLabel
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TaskSearchRequest model module.
 * @module model/TaskSearchRequest
 * @version 0.1.0
 */
class TaskSearchRequest {
    /**
     * Constructs a new <code>TaskSearchRequest</code>.
     * @alias module:model/TaskSearchRequest
     */
    constructor() { 
        
        TaskSearchRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TaskSearchRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TaskSearchRequest} obj Optional instance to populate.
     * @return {module:model/TaskSearchRequest} The populated <code>TaskSearchRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaskSearchRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('credits')) {
                obj['credits'] = ApiClient.convertToType(data['credits'], 'Number');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('requesters')) {
                obj['requesters'] = ApiClient.convertToType(data['requesters'], ['String']);
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('credits_min')) {
                obj['credits_min'] = ApiClient.convertToType(data['credits_min'], 'Number');
            }
            if (data.hasOwnProperty('credits_max')) {
                obj['credits_max'] = ApiClient.convertToType(data['credits_max'], 'Number');
            }
            if (data.hasOwnProperty('sort_criteria')) {
                obj['sort_criteria'] = ApiClient.convertToType(data['sort_criteria'], 'String');
            }
            if (data.hasOwnProperty('sort_ascending')) {
                obj['sort_ascending'] = ApiClient.convertToType(data['sort_ascending'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TaskSearchRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TaskSearchRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['requesters'])) {
            throw new Error("Expected the field `requesters` to be an array in the JSON data but got " + data['requesters']);
        }
        // ensure the json data is a string
        if (data['sort_criteria'] && !(typeof data['sort_criteria'] === 'string' || data['sort_criteria'] instanceof String)) {
            throw new Error("Expected the field `sort_criteria` to be a primitive type in the JSON string but got " + data['sort_criteria']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
TaskSearchRequest.prototype['name'] = undefined;

/**
 * @member {Number} credits
 */
TaskSearchRequest.prototype['credits'] = undefined;

/**
 * @member {Array.<String>} tags
 */
TaskSearchRequest.prototype['tags'] = undefined;

/**
 * @member {Array.<String>} requesters
 */
TaskSearchRequest.prototype['requesters'] = undefined;

/**
 * @member {Number} page
 */
TaskSearchRequest.prototype['page'] = undefined;

/**
 * @member {Number} credits_min
 */
TaskSearchRequest.prototype['credits_min'] = undefined;

/**
 * @member {Number} credits_max
 */
TaskSearchRequest.prototype['credits_max'] = undefined;

/**
 * @member {String} sort_criteria
 */
TaskSearchRequest.prototype['sort_criteria'] = undefined;

/**
 * @member {Boolean} sort_ascending
 */
TaskSearchRequest.prototype['sort_ascending'] = undefined;






export default TaskSearchRequest;

